package com.raitonbl.hermes.smsc.sdk;


public interface HermesSystemConstants {
    // COMMON
    String KV_CACHE_NAME="kvCache";
    String ROUTE_PREFIX = "HERMES_SMSC";
    String SYSTEM_ROUTE_PREFIX = ROUTE_PREFIX + "_SYS_";
    String INTERNAL_ROUTE_PREFIX = ROUTE_PREFIX + "_INTERNAL_";

    // SMPP DECIDER ROUTE(S)
    String SMPP_DECIDER_ROUTE = HermesSystemConstants.INTERNAL_ROUTE_PREFIX + "_GET_TARGET_FROM_POLICIES";
    String DIRECT_TO_SMPP_DECIDER_ROUTE = "direct:" + SMPP_DECIDER_ROUTE;

    // REPOSITORY ROUTE(S)
    String GET_ALL_SMPP_CONNECTIONS_ROUTE = INTERNAL_ROUTE_PREFIX + "_SMPP_CONNECTION_REPOSITORY_GET_ALL";
    String DIRECT_TO_GET_ALL_SMPP_CONNECTIONS_ROUTE = "direct:"+ GET_ALL_SMPP_CONNECTIONS_ROUTE;

}
