package com.raitonbl.hermes.smsc.sdk;


public interface HermesSystemConstants {
    // COMMON(S)
    String KV_CACHE_NAME = "kvCache";
    String ROUTE_PREFIX = "HERMES_SMSC";
    String SYSTEM_ROUTE_PREFIX = ROUTE_PREFIX + "_SYS_";
    String INTERNAL_ROUTE_PREFIX = ROUTE_PREFIX + "_INTERNAL_";
    // SEND SMS REQUEST ROUTE(S)
    String SEND_SMS_REQUEST_ROUTE = HermesSystemConstants.SYSTEM_ROUTE_PREFIX + "SEND_MESSAGE";
    String DIRECT_TO_SEND_SMS_REQUEST_ROUTE = "direct:" + SEND_SMS_REQUEST_ROUTE;

    // SMPP DECIDER ROUTE(S)
    String SMPP_DECIDER_ROUTE = INTERNAL_ROUTE_PREFIX + "GET_TARGET_FROM_POLICIES";
    String DIRECT_TO_SMPP_DECIDER_ROUTE = "direct:" + SMPP_DECIDER_ROUTE;

    // REPOSITORY ROUTE(S)
    String GET_ALL_SMPP_CONNECTIONS_ROUTE = INTERNAL_ROUTE_PREFIX + "SMPP_CONNECTION_REPOSITORY_GET_ALL";
    String DIRECT_TO_GET_ALL_SMPP_CONNECTIONS_ROUTE = "direct:" + GET_ALL_SMPP_CONNECTIONS_ROUTE;

    // POLICY ROUTES(S)
    String READ_POLICIES_FROM_DATASOURCE_ROUTE = SYSTEM_ROUTE_PREFIX + "POLICY_READ";
    String DIRECT_TO_READ_POLICIES_FROM_DATASOURCE_ROUTE = "direct:" + READ_POLICIES_FROM_DATASOURCE_ROUTE;
    String UPDATE_POLICIES_ON_DATASOURCE_ROUTE = SYSTEM_ROUTE_PREFIX + "POLICY_UPDATE";
    String DIRECT_TO_UPDATE_POLICIES_ON_DATASOURCE_ROUTE = "direct:" + UPDATE_POLICIES_ON_DATASOURCE_ROUTE;

    // SMPP CONNECTION ROUTE(S)
    String SMPP_CONNECTION_RECEIVER_ROUTE_ID_FORMAT = SYSTEM_ROUTE_PREFIX + "%s_RECEIVER_CONNECTION";
    String SMPP_CONNECTION_TRANSMITTER_ROUTE_ID_FORMAT = SYSTEM_ROUTE_PREFIX + "%s_TRANSMITTER_CONNECTION";
    String DIRECT_TO_SMPP_CONNECTION_TRANSMITTER_ROUTE_ID_FORMAT = "direct:"+ SMPP_CONNECTION_TRANSMITTER_ROUTE_ID_FORMAT;

}
