package com.raitonbl.hermes.smsc.camel.common;


public interface HermesSystemConstants  {

    // COMMON(S)
    String KV_CACHE_NAME = "kvCache";
    String ROUTE_PREFIX = "HERMES_SMSC";
    String SYSTEM_ROUTE_PREFIX = ROUTE_PREFIX + "_SYS_";
    String INTERNAL_ROUTE_PREFIX = ROUTE_PREFIX + "_INTERNAL_";

    // REPOSITORY ROUTE(S)
    String SMPP_REPOSITORY_ROUTE_PREFIX = SYSTEM_ROUTE_PREFIX + "SMPP_CONNECTION_REPOSITORY";
    String GET_ALL_SMPP_CONNECTIONS_ROUTE = SMPP_REPOSITORY_ROUTE_PREFIX + "_GET_ALL";
    String DIRECT_TO_GET_ALL_SMPP_CONNECTIONS_ROUTE = "direct:" + GET_ALL_SMPP_CONNECTIONS_ROUTE;
    String FIND_SMPP_CONNECTION_BY_ID = GET_ALL_SMPP_CONNECTIONS_ROUTE + "%s_FIND_BY_ID";
    String DIRECT_TO_FIND_SMPP_CONNECTION_BY_ID = "direct:" + FIND_SMPP_CONNECTION_BY_ID;

    interface Operations{
        String SEND_SMS_REQUEST_ROUTE_PREFIX = "SEND_MESSAGE";
        String SEND_MESSAGE_SYSTEM_ROUTE = SYSTEM_ROUTE_PREFIX + SEND_SMS_REQUEST_ROUTE_PREFIX;
        String DIRECT_TO_SEND_MESSAGE_SYSTEM_ROUTE = "direct:" + SEND_MESSAGE_SYSTEM_ROUTE;

        String SMPP_DECIDER_SYSTEM_ROUTE = SYSTEM_ROUTE_PREFIX + "GET_TARGET_FROM_POLICIES";
        String DIRECT_TO_SMPP_DECIDER_SYSTEM_ROUTE = "direct:" + SMPP_DECIDER_SYSTEM_ROUTE;
    }

    interface Policies {
        String ADD_POLICIES_FROM_DATASOURCE_SYSTEM_ROUTE = SYSTEM_ROUTE_PREFIX + "POLICY_ADD";
        String DIRECT_TO_ADD_POLICIES_FROM_DATASOURCE_SYSTEM_ROUTE = "direct:" + ADD_POLICIES_FROM_DATASOURCE_SYSTEM_ROUTE;
        String FIND_POLICIES_FROM_DATASOURCE_SYSTEM_ROUTE = SYSTEM_ROUTE_PREFIX + "POLICY_FIND_ALL";
        String DIRECT_TO_FIND_POLICIES_FROM_DATASOURCE_SYSTEM_ROUTE = "direct:" + FIND_POLICIES_FROM_DATASOURCE_SYSTEM_ROUTE;
        String FIND_POLICY_BY_ID_FROM_DATASOURCE_SYSTEM_ROUTE = SYSTEM_ROUTE_PREFIX + "POLICY_FIND_BY_ID";
        String DIRECT_TO_FIND_POLICY_BY_ID_FROM_DATASOURCE_SYSTEM_ROUTE = "direct:" + FIND_POLICY_BY_ID_FROM_DATASOURCE_SYSTEM_ROUTE;
        String UPDATE_POLICY_ON_DATASOURCE_ROUTE = SYSTEM_ROUTE_PREFIX + "POLICY_UPDATE";
        String DIRECT_TO_UPDATE_POLICY_ON_DATASOURCE_ROUTE = "direct:" + UPDATE_POLICY_ON_DATASOURCE_ROUTE;
        String DELETE_POLICY_BY_ID_ON_DATASOURCE_ROUTE = SYSTEM_ROUTE_PREFIX + "POLICY_DELETE_BY_ID";
        String DIRECT_TO_DELETE_POLICY_BY_ID_ON_DATASOURCE_ROUTE = "direct:" + DELETE_POLICY_BY_ID_ON_DATASOURCE_ROUTE;
        String POLICY_LIFECYCLE_MANAGER_ROUTE = SYSTEM_ROUTE_PREFIX + "POLICY_MANAGE_LIFECYCLE";
    }

    interface SmppConnection {
        String SMPP_CONNECTION_LIFECYCLE_MANAGER_ROUTE = INTERNAL_ROUTE_PREFIX + "SMPP_CONNECTION_MANAGE_LIFECYCLE";
        String SMPP_CONNECTION_RECEIVER_ROUTE_ID_FORMAT = INTERNAL_ROUTE_PREFIX + "%s_RECEIVER_CONNECTION";
        String SMPP_CONNECTION_TRANSMITTER_ROUTE_ID_FORMAT = INTERNAL_ROUTE_PREFIX + "%s_TRANSMITTER_CONNECTION";
        String SMPP_CONNECTION_TRANSCEIVER_CALLBACK_FORMAT = HermesSystemConstants.INTERNAL_ROUTE_PREFIX + "%s_TRANSCEIVER_CALLBACK";
        String DIRECT_TO_SMPP_CONNECTION_TRANSMITTER_ROUTE_ID_FORMAT = "direct:" + SMPP_CONNECTION_TRANSMITTER_ROUTE_ID_FORMAT;
    }

    interface Security{
        String OPENID_CONNECT_GET_AUTHENTICATION = INTERNAL_ROUTE_PREFIX + "OPENID_CONNECT_GET_AUTHENTICATION";
        String DIRECT_TO_OPENID_CONNECT_GET_AUTHENTICATION = "direct:" + OPENID_CONNECT_GET_AUTHENTICATION;
    }

    interface Repository{
        // NEW REPOSITORY
        String REPOSITORY_FIND_ALL = INTERNAL_ROUTE_PREFIX + "REPOSITORY_FIND_ALL";
        String DIRECT_TO_REPOSITORY_FIND_ALL = "direct:" + REPOSITORY_FIND_ALL;
        String REPOSITORY_CREATE = INTERNAL_ROUTE_PREFIX + "REPOSITORY_ADD";
        String DIRECT_TO_REPOSITORY_CREATE = "direct:" + REPOSITORY_CREATE;
        String REPOSITORY_FIND_BY_ID = INTERNAL_ROUTE_PREFIX + "REPOSITORY_FIND_BY_ID";
        String DIRECT_TO_REPOSITORY_FIND_BY_ID = "direct:" + REPOSITORY_FIND_BY_ID;
        String REPOSITORY_UPDATE_BY_ID = INTERNAL_ROUTE_PREFIX + "REPOSITORY_EDIT_BY_ID";
        String DIRECT_TO_REPOSITORY_UPDATE_BY_ID = "direct:" + REPOSITORY_UPDATE_BY_ID;
        String REPOSITORY_DELETE_BY_ID = INTERNAL_ROUTE_PREFIX + "REPOSITORY_DELETE_BY_ID";
        String DIRECT_TO_REPOSITORY_DELETE_BY_ID = "direct:" + REPOSITORY_DELETE_BY_ID;
    }

    interface AsyncApi{
        String ASYNCAPI_ROUTE_PREFIX = ROUTE_PREFIX + "_ASYNCAPI_";
        String SEND_MESSAGE_THROUGH_ASYNCAPI_INTERFACE = ASYNCAPI_ROUTE_PREFIX + Operations.SEND_SMS_REQUEST_ROUTE_PREFIX;
    }

    interface RestApi {
        String RESTAPI_ROUTE_PREFIX = ROUTE_PREFIX + "_RESTAPI_";

        // SHORT MESSAGES
        String SEND_SHORT_MESSAGE_OPERATION = "SendShortMessage";
        String SEND_MESSAGE_THROUGH_HTTP_INTERFACE = RESTAPI_ROUTE_PREFIX + SEND_SHORT_MESSAGE_OPERATION;

        // SMPP CONNECTIONS
        String ADD_SMPP_CONNECTION_OPERATION = "AddSmppConnection";
        String GET_SMPP_CONNECTIONS_OPERATION = "GetSmppConnections";
        String GET_SMPP_CONNECTION_BY_ID_OPERATION = "GetSmppConnectionById";
        String UPDATE_SMPP_CONNECTION_BY_ID_OPERATION = "ConfigureSmppConnectionById";
        String DELETE_SMPP_CONNECTION_BY_ID_OPERATION = "RemoveSmppConnectionById";
        String CREATE_SMPP_CONNECTION_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + ADD_SMPP_CONNECTION_OPERATION;
        String GET_SMPP_CONNECTION_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + GET_SMPP_CONNECTION_BY_ID_OPERATION;
        String REMOVE_SMPP_CONNECTION_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + DELETE_SMPP_CONNECTION_BY_ID_OPERATION;
        String UPDATE_SMPP_CONNECTION_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + UPDATE_SMPP_CONNECTION_BY_ID_OPERATION;
        String GET_SMPP_CONNECTIONS_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + GET_SMPP_CONNECTIONS_OPERATION ;

        // POLICIES
        String ADD_POLICIES_OPERATION = "AddPolicy";
        String GET_POLICIES_OPERATION = "GetPolicies";
        String GET_POLICY_BY_ID_OPERATION = "GetPolicyById";
        String UPDATE_POLICY_BY_ID_OPERATION = "UpdatePolicyById";
        String DELETE_POLICY_BY_ID_OPERATION = "RemovePolicyById";
        String CREATE_POLICY_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + ADD_POLICIES_OPERATION;
        String GET_POLICY_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + GET_POLICY_BY_ID_OPERATION;
        String REMOVE_POLICY_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + DELETE_POLICY_BY_ID_OPERATION;
        String UPDATE_POLICIES_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + UPDATE_POLICY_BY_ID_OPERATION;
        String GET_ALL_POLICIES_RESTAPI_ROUTE = RESTAPI_ROUTE_PREFIX + GET_POLICIES_OPERATION;
    }
}
